interface Language {
    label: string;
    value: string;
}

export const languages = [
    { label: "Afrikaans", value: "af" },
    { label: "Amharic", value: "am" },
    { label: "Arabic", value: "ar" },
    { label: "Assamese", value: "as" },
    { label: "Azerbaijani", value: "az" },
    { label: "Belarusian", value: "be" },
    { label: "Bulgarian", value: "bg" },
    { label: "Bhojpuri", value: "bho" },
    { label: "Bengali", value: "bn" },
    { label: "Bosnian", value: "bs" },
    { label: "Catalan, Valencian", value: "ca" },
    { label: "Cebuano", value: "ceb" },
    { label: "Czech", value: "cs" },
    { label: "Danish", value: "da" },
    { label: "German", value: "de" },
    { label: "English", value: "en" },
    { label: "Turkish", value: "tr" },
    { label: "Ewe", value: "ee" },
    { label: "Greek, Modern", value: "el" },
    { label: "Spanish", value: "es" },
    { label: "Estonian", value: "et" },
    { label: "Basque", value: "eu" },
    { label: "Persian", value: "fa" },
    { label: "Fula", value: "ff" },
    { label: "Finnish", value: "fi" },
    { label: "French", value: "fr" },
    { label: "Irish", value: "ga" },
    { label: "Galician", value: "gl" },
    { label: "Guarani", value: "gn" },
    { label: "Gujarati", value: "gu" },
    { label: "Hausa", value: "ha" },
    { label: "Haitian Creole", value: "ht" },
    { label: "Hebrew (modern)", value: "he" },
    { label: "Hindi", value: "hi" },
    { label: "Chhattisgarhi", value: "hne" },
    { label: "Croatian", value: "hr" },
    { label: "Hungarian", value: "hu" },
    { label: "Armenian", value: "hy" },
    { label: "Indonesian", value: "id" },
    { label: "Igbo", value: "ig" },
    { label: "Icelandic", value: "is" },
    { label: "Italian", value: "it" },
    { label: "Japanese", value: "ja" },
    { label: "Syro-Palestinian Sign Language", value: "sypl" },
    { label: "Javanese", value: "jv" },
    { label: "Georgian", value: "ka" },
    { label: "Kikuyu", value: "ki" },
    { label: "Kyrgyz", value: "ky" },
    { label: "Kuanyama", value: "kj" },
    { label: "Kazakh", value: "kk" },
    { label: "Khmer", value: "km" },
    { label: "Kannada", value: "kn" },
    { label: "Korean", value: "ko" },
    { label: "Krio", value: "kri" },
    { label: "Kashmiri", value: "ks" },
    { label: "Kurdish", value: "ku" },
    { label: "Latin", value: "la" },
    { label: "Lithuanian", value: "lt" },
    { label: "Luxembourgish", value: "lb" },
    { label: "Latvian", value: "lv" },
    { label: "Magahi", value: "mag" },
    { label: "Maithili", value: "mai" },
    { label: "Malagasy", value: "mg" },
    { label: "Macedonian", value: "mk" },
    { label: "Malayalam", value: "ml" },
    { label: "Mongolian", value: "mn" },
    { label: "Marathi (Marāṭhī)", value: "mr" },
    { label: "Malay", value: "ms" },
    { label: "Maltese", value: "mt" },
    { label: "Burmese", value: "my" },
    { label: "Nepali", value: "ne" },
    { label: "Dutch", value: "nl" },
    { label: "Norwegian", value: "no" },
    { label: "Oromo", value: "om" },
    { label: "Odia", value: "or" },
    { label: "Panjabi, Punjabi", value: "pa" },
    { label: "Polish", value: "pl" },
    { label: "Pashto", value: "ps" },
    { label: "Portuguese", value: "pt" },
    { label: "Rundi", value: "rn" },
    { label: "Romanian, Moldavian, Moldovan", value: "ro" },
    { label: "Russian", value: "ru" },
    { label: "Kinyarwanda", value: "rw" },
    { label: "Sindhi", value: "sd" },
    { label: "Argentine Sign Language", value: "asl" },
    { label: "Brazilian Sign Language", value: "bsl" },
    { label: "Chinese Sign Language", value: "csl" },
    { label: "Colombian Sign Language", value: "cosl" },
    { label: "German Sign Language", value: "gsl" },
    { label: "Algerian Sign Language", value: "asl" },
    { label: "Ecuadorian Sign Language", value: "ecsl" },
    { label: "Spanish Sign Language", value: "ssl" },
    { label: "Ethiopian Sign Language", value: "etsl" },
    { label: "French Sign Language", value: "fsl" },
    { label: "British Sign Language", value: "bsl" },
    { label: "Ghanaian Sign Language", value: "ghsl" },
    { label: "Irish Sign Language", value: "isl" },
    { label: "Indopakistani Sign Language", value: "ipsl" },
    { label: "Persian Sign Language", value: "psl" },
    { label: "Italian Sign Language", value: "itlsl" },
    { label: "Japanese Sign Language", value: "jpsl" },
    { label: "Kenyan Sign Language", value: "ksl" },
    { label: "Korean Sign Language", value: "kosl" },
    { label: "Moroccan Sign Language", value: "mosl" },
    { label: "Mexican Sign Language", value: "mxsl" },
    { label: "Malaysian Sign Language", value: "mysl" },
    { label: "Philippine Sign Language", value: "phsl" },
    { label: "Polish Sign Language", value: "plsl" },
    { label: "Portuguese Sign Language", value: "ptsl" },
    { label: "Russian Sign Language", value: "rusl" },
    { label: "Saudi Arabian Sign Language", value: "sasl" },
    { label: "El Salvadoran Sign Language", value: "essl" },
    { label: "Turkish Sign Language", value: "trsl" },
    { label: "Tanzanian Sign Language", value: "tzsl" },
    { label: "Ukrainian Sign Language", value: "uksl" },
    { label: "American Sign Language", value: "asls" },
    { label: "South African Sign Language", value: "sasl" },
    { label: "Zimbabwe Sign Language", value: "zbsl" },
    { label: "Sinhala, Sinhalese", value: "si" },
    { label: "Slovak", value: "sk" },
    { label: "Saraiki", value: "skr" },
    { label: "Slovene", value: "sl" },
    { label: "Shona", value: "sn" },
    { label: "Somali", value: "so" },
    { label: "Albanian", value: "sq" },
    { label: "Serbian", value: "sr" },
    { label: "Swati", value: "ss" },
    { label: "Sunda", value: "su" },
    { label: "Swedish", value: "sv" },
    { label: "Swahili", value: "sw" },
    { label: "Sylheti", value: "syl" },
    { label: "Tamil", value: "ta" },
    { label: "Telugu", value: "te" },
    { label: "Tagalog", value: "tl" },
    { label: "Thai", value: "th" },
    { label: "Tibetan", value: "bo" },
    { label: "Tigrinya", value: "ti" },
    { label: "Turkmen", value: "tk" },
    { label: "Tswana", value: "tn" },
    { label: "Uyghur", value: "ug" },
    { label: "Ukrainian", value: "uk" },
    { label: "Urdu", value: "ur" },
    { label: "Uzbek", value: "uz" },
    { label: "Vietnamese", value: "vi" },
    { label: "Xhosa", value: "xh" },
    { label: "Yiddish", value: "yi" },
    { label: "Yoruba", value: "yo" },
    { label: "Cantonese", value: "yue" },
    { label: "Chinese", value: "zh" },
    { label: "Zulu", value: "zu" },
] as Language[];

export function getLanguageLabel(value: string): string | undefined {
    const language = languages.find(lang => lang.value === value);
    return language ? language.label : undefined;
}